language: java
branches:
  only:
    - master
    - Develop
    - feature/feature-14-registry
notifications:
  email:
    - murugesm@indiana.edu
    - rraavi@indiana.edu
    - srameshv@indiana.edu
    - jbhalla@indiana.edu
jdk:
  - oraclejdk8
sudo: false
install: true
script: cd "core/java/registry" && mvn clean install -DskipTests=true
