language: java
branches:
  only:
    - master
    - Develop
    - feature/feature-14-registry
notifications:
  email:
    - murugesm@indiana.edu
    - rraavi@indiana.edu
    - srameshv@indiana.edu
    - jbhalla@indiana.edu
jdk:
  - oraclejdk8
sudo: false
install: true
script: cd "core/java/registry" && mvn clean install -DskipTests=true

before_deploy:
  - cd ../core/java/
  - zip -r TeamBash_registry.zip registry || true
  - mkdir -p "registry_upload"
  - mv TeamBash_registry.zip registry_upload/TeamBash_registry.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: team-bash
    local_dir: registry_upload
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: feature/feature-14-registry