version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/registryService
hooks:
  BeforeInstall:
    - location: registryService/scripts/before-install.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: registryService/scripts/install.sh
      timeout: 180
      runas: root